<script lang="ts">
  let custodianName = $state('');
  let custodianTitle = $state('Records Custodian');
  let entityName = $state('');
  let publicKey = $state('');
  let jurisdiction = $state('California');
  let recordCount = $state('247');
  let copied = $state(false);

  const today = new Date().toISOString().slice(0, 10);

  let certification = $derived(buildCertification());

  function buildCertification(): string {
    const name = custodianName || '[Full Name]';
    const title = custodianTitle || '[Title]';
    const entity = entityName || '[Operator Entity]';
    const key = publicKey || '[64 hex character Ed25519 public key]';
    const jur = jurisdiction || '[Jurisdiction]';
    const count = recordCount || '[N]';

    return `CERTIFICATION OF RECORDS GENERATED BY AN ELECTRONIC PROCESS OR SYSTEM
Pursuant to Federal Rule of Evidence 902(13) and Rule 902(11)

I, ${name}, hereby certify the following:

1. I am the ${title} for ${entity}. I am a qualified person
   with personal knowledge of the electronic process and system described below.

2. The attached records are true and correct copies of records generated by the
   Project AIR logging system operated by ${entity} in the regular course of
   business.

3. The records are stored in the AgDR (AI Decision Record) v0.2 format, a
   structured append-only log in which each record contains:

   a. a UUIDv7 step identifier and ISO 8601 timestamp;
   b. the kind of agent step (llm_start, llm_end, tool_start, tool_end,
      agent_finish, or agent_message);
   c. a structured payload describing the step;
   d. the BLAKE3 hash of the preceding record's payload (prev_hash);
   e. the BLAKE3 hash of this record's canonicalised payload (content_hash); and
   f. an Ed25519 digital signature (RFC 8032) over the concatenation of
      prev_hash and content_hash, produced with a private key held under sole
      control of ${entity}.

4. Each record is cryptographically linked to the preceding record by its hash.
   Any alteration, insertion, deletion, or reordering of records is detected
   deterministically by signature verification using the open-source Project
   AIR verifier (air trace), which reports the exact record at which the chain
   breaks.

5. The records were written at or near the time of the events they describe by
   the Project AIR instrumentation deployed in the regular course of
   ${entity}'s operations. The records have been retained and preserved
   according to ${entity}'s records retention policy.

6. The Ed25519 public key corresponding to the signing key used to produce the
   attached records is:

   ${key}

7. The attached records have been verified using the "air trace" command. The
   verification output is attached as Exhibit A to this certification. The
   chain verified with status "ok" for ${count} records.

8. The cryptographic primitives used are industry-standard, open, and
   independently reproducible. Ed25519 is specified in RFC 8032. BLAKE3 is
   specified in the BLAKE3 reference specification. The Project AIR verifier
   source code is MIT-licensed and available at
   https://github.com/get-sltr/vindicara-ai.

I declare under penalty of perjury under the laws of ${jur} that the
foregoing is true and correct.

Executed on ${today} at [Location].


_________________________________
${name}
${title}
${entity}
`;
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(certification);
      copied = true;
      setTimeout(() => (copied = false), 2000);
    } catch {
      copied = false;
    }
  }

  function downloadMarkdown() {
    const blob = new Blob([certification], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fre-902-13-certification-${today}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
</script>

<div class="grid lg:grid-cols-2 gap-6">
  <!-- Form -->
  <div class="glass-panel rounded-lg p-6">
    <div class="flex items-center gap-2 mb-5">
      <span class="font-mono text-[10px] uppercase tracking-[0.18em] text-brand-red">inputs</span>
      <span class="text-xs text-zinc-500">Your details fill the template live.</span>
    </div>

    <div class="space-y-4">
      <div>
        <label class="block font-mono text-[10px] uppercase tracking-wider text-zinc-400 mb-1.5" for="cg-name">
          Custodian full name
        </label>
        <input
          id="cg-name"
          type="text"
          bind:value={custodianName}
          placeholder="Jane Doe"
          class="w-full bg-obsidian-lighter border border-white/10 focus:border-brand-red rounded px-3 py-2 text-sm font-mono text-white outline-none transition-colors"
        />
      </div>

      <div>
        <label class="block font-mono text-[10px] uppercase tracking-wider text-zinc-400 mb-1.5" for="cg-title">
          Custodian title
        </label>
        <input
          id="cg-title"
          type="text"
          bind:value={custodianTitle}
          placeholder="Records Custodian"
          class="w-full bg-obsidian-lighter border border-white/10 focus:border-brand-red rounded px-3 py-2 text-sm font-mono text-white outline-none transition-colors"
        />
      </div>

      <div>
        <label class="block font-mono text-[10px] uppercase tracking-wider text-zinc-400 mb-1.5" for="cg-entity">
          Operator entity (legal name)
        </label>
        <input
          id="cg-entity"
          type="text"
          bind:value={entityName}
          placeholder="Acme Technologies, Inc."
          class="w-full bg-obsidian-lighter border border-white/10 focus:border-brand-red rounded px-3 py-2 text-sm font-mono text-white outline-none transition-colors"
        />
      </div>

      <div>
        <label class="block font-mono text-[10px] uppercase tracking-wider text-zinc-400 mb-1.5" for="cg-key">
          Ed25519 public key (64 hex chars)
        </label>
        <input
          id="cg-key"
          type="text"
          bind:value={publicKey}
          placeholder="7c3d9a1e4b8c2f5d7a3e9b1c4d6f8a2e5b7c9d1f3a5e7b9c1d3f5a7e9b1c3d5f"
          class="w-full bg-obsidian-lighter border border-white/10 focus:border-brand-red rounded px-3 py-2 text-sm font-mono text-white outline-none transition-colors"
        />
      </div>

      <div class="grid grid-cols-2 gap-3">
        <div>
          <label class="block font-mono text-[10px] uppercase tracking-wider text-zinc-400 mb-1.5" for="cg-jur">
            Jurisdiction
          </label>
          <input
            id="cg-jur"
            type="text"
            bind:value={jurisdiction}
            placeholder="California"
            class="w-full bg-obsidian-lighter border border-white/10 focus:border-brand-red rounded px-3 py-2 text-sm font-mono text-white outline-none transition-colors"
          />
        </div>
        <div>
          <label class="block font-mono text-[10px] uppercase tracking-wider text-zinc-400 mb-1.5" for="cg-count">
            Verified record count
          </label>
          <input
            id="cg-count"
            type="text"
            bind:value={recordCount}
            placeholder="247"
            class="w-full bg-obsidian-lighter border border-white/10 focus:border-brand-red rounded px-3 py-2 text-sm font-mono text-white outline-none transition-colors"
          />
        </div>
      </div>
    </div>

    <div class="mt-5 text-[11px] text-zinc-500 leading-relaxed">
      This template is adapted from FRE 902(13). It is a starting point, not legal advice.
      Have qualified counsel review before you file or serve it.
    </div>
  </div>

  <!-- Output -->
  <div class="glass-panel rounded-lg overflow-hidden flex flex-col">
    <div
      class="border-b border-white/10 px-4 py-3 flex items-center justify-between bg-black/30"
    >
      <span class="font-mono text-[10px] uppercase tracking-[0.18em] text-zinc-500">
        fre-902-13-certification.md
      </span>
      <div class="flex gap-2">
        <button
          type="button"
          onclick={copyToClipboard}
          class="font-mono text-[11px] uppercase tracking-wider px-3 py-1 border border-white/15 rounded hover:border-brand-red hover:text-brand-red transition-colors"
        >
          {copied ? 'copied' : 'copy'}
        </button>
        <button
          type="button"
          onclick={downloadMarkdown}
          class="font-mono text-[11px] uppercase tracking-wider px-3 py-1 bg-brand-red text-white rounded hover:bg-brand-red-dark transition-colors"
        >
          download .md
        </button>
      </div>
    </div>
    <pre
      class="font-mono text-[11px] leading-relaxed text-zinc-300 p-4 overflow-auto max-h-[560px] whitespace-pre-wrap">{certification}</pre>
  </div>
</div>
