<script lang="ts">
  type Claim = {
    title: string;
    body: string;
    airProvides: string;
    sourceLabel: string;
    sourceUrl: string;
  };

  type Framework = {
    id: string;
    short: string;
    region: string;
    label: string;
    summary: string;
    claims: Claim[];
  };

  const FRAMEWORKS: Framework[] = [
    {
      id: 'fre',
      short: 'US FRE',
      region: 'United States',
      label: 'Federal Rules of Evidence',
      summary:
        'The procedural rules federal courts apply to authenticate and admit electronic records.',
      claims: [
        {
          title: 'FRE 901(a): general authentication',
          body: 'The proponent must produce evidence sufficient to support a finding that the item is what the proponent claims it is.',
          airProvides:
            'Every record carries an Ed25519 signature and embedded public key. Any verifier can confirm the record is what it claims to be, offline, using RFC 8032.',
          sourceLabel: 'FRE 901',
          sourceUrl: 'https://www.law.cornell.edu/rules/fre/rule_901',
        },
        {
          title: 'FRE 901(b)(9): process or system',
          body: 'Evidence describing a process or system and showing that it produces an accurate result.',
          airProvides:
            'The hashing and signing process is deterministic and reproducible. Same inputs produce the same hashes and signatures. An expert witness can describe, demonstrate, and have the demonstration independently reproduced.',
          sourceLabel: 'BLAKE3 + RFC 8032',
          sourceUrl: 'https://github.com/BLAKE3-team/BLAKE3-specs',
        },
        {
          title: 'FRE 902(13): self-authenticating electronic records',
          body: 'A record generated by an electronic process or system that produces an accurate result, as shown by a certification of a qualified person.',
          airProvides:
            'Records from the AIR chain accompanied by a qualified custodian certification (template generator above) self-authenticate. No live witness required.',
          sourceLabel: 'FRE 902',
          sourceUrl: 'https://www.law.cornell.edu/rules/fre/rule_902',
        },
        {
          title: 'FRE 803(6): business records exception',
          body: 'Records created in the regular course of business, near the time of events, kept by someone with knowledge.',
          airProvides:
            'Continuous instrumentation pattern: AIR writes records at the time the agent acts, as part of normal operations. Meets the "regularly conducted activity" bar when deployed as documented.',
          sourceLabel: 'FRE 803',
          sourceUrl: 'https://www.law.cornell.edu/rules/fre/rule_803',
        },
        {
          title: 'FRE 1001-1004: best evidence rule',
          body: 'An "original" ESI includes any printout or output that accurately reflects the information. Duplicates are admissible unless authenticity is challenged.',
          airProvides:
            'forensic-report.json is an accurate, human-readable reflection of the signed chain. Admissible under FRE 1003 provided the chain is preserved.',
          sourceLabel: 'FRE 1001-1004',
          sourceUrl: 'https://www.law.cornell.edu/rules/fre/rule_1001',
        },
      ],
    },
    {
      id: 'eidas',
      short: 'EU eIDAS',
      region: 'European Union',
      label: 'eIDAS Regulation (EU) No 910/2014',
      summary:
        'The EU framework governing the legal effect of electronic signatures and trust services.',
      claims: [
        {
          title: 'Article 25(1): non-discrimination',
          body: 'An electronic signature shall not be denied legal effect and admissibility solely on the grounds that it is electronic or does not meet qualified-signature requirements.',
          airProvides:
            'AIR\'s Ed25519 signatures qualify as electronic signatures under Article 3(10). They cannot be refused admissibility purely because they are electronic.',
          sourceLabel: 'Regulation 910/2014',
          sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.257.01.0073.01.ENG',
        },
        {
          title: 'Article 26: advanced electronic signatures',
          body: 'Signatures that are uniquely linked to the signatory, capable of identifying them, under their sole control, and detectable if data is altered.',
          airProvides:
            'Requirement (d) (detection of alteration) is satisfied by construction: any change breaks the chain. Requirements (a), (b), (c) depend on the operator\'s key-management policy. When operators hold the signing key under sole control, AIR produces advanced electronic signatures.',
          sourceLabel: 'Article 26',
          sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.257.01.0073.01.ENG',
        },
        {
          title: 'Article 3(12): qualified electronic signatures',
          body: 'Advanced signatures created using a qualified certificate from a Qualified Trust Service Provider (QTSP). Legal force equivalent to handwritten signatures.',
          airProvides:
            'Not provided by default. AIR is cryptographically agnostic to the key source. Operators needing qualified status obtain a qualified certificate from a QTSP on the EU Trusted List and use its key as the AIR signing key.',
          sourceLabel: 'EU Trusted List',
          sourceUrl: 'https://esignature.ec.europa.eu/efda/tl-browser/',
        },
      ],
    },
    {
      id: 'ai-act',
      short: 'EU AI Act',
      region: 'European Union',
      label: 'EU AI Act (Regulation 2024/1689)',
      summary:
        'Risk-tiered regulation of AI systems in the EU market. High-risk systems enforceable 2 August 2026.',
      claims: [
        {
          title: 'Article 72: post-market monitoring',
          body: 'Providers of high-risk AI systems must establish a post-market monitoring system proportionate to the technology and risks, actively collecting and analysing performance data throughout the system\'s lifetime.',
          airProvides:
            'Every agent step is recorded, integrity-protected, and verifiable. air report --article-72 produces a monitoring report template populated from the chain.',
          sourceLabel: 'Regulation 2024/1689',
          sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
        },
        {
          title: 'Article 12: record-keeping',
          body: 'High-risk AI systems must automatically record events (logs) over their entire lifecycle.',
          airProvides:
            'The AIR record is that log. Structured, signed, and long-term verifiable. Article 12 is the foundation; Article 72 is the ongoing obligation built on top of it.',
          sourceLabel: 'Article 12',
          sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
        },
        {
          title: 'Penalties: up to 7% of global revenue',
          body: 'Non-compliance with high-risk system requirements carries fines higher than GDPR (which tops out at 4%).',
          airProvides:
            'AIR instrumentation, combined with a documented retention and key-management policy, is the fastest path from zero to demonstrable conformity.',
          sourceLabel: 'Article 99',
          sourceUrl: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
        },
      ],
    },
    {
      id: 'gdpr',
      short: 'GDPR',
      region: 'European Union',
      label: 'General Data Protection Regulation',
      summary:
        'Where an AI agent processes personal data, controllers and processors carry record-keeping obligations.',
      claims: [
        {
          title: 'Article 30: records of processing activities',
          body: 'Controllers and processors must maintain records of processing, including purpose, categories of data, data processors, and timing.',
          airProvides:
            'The AIR chain documents purpose (user_intent), data categories (tool arguments and outputs), processors (agent identities), and timestamps. It is evidence for agent-mediated processing, not a full Article 30 register substitute.',
          sourceLabel: 'GDPR Article 30',
          sourceUrl: 'https://gdpr-info.eu/art-30-gdpr/',
        },
      ],
    },
    {
      id: 'other',
      short: 'Other',
      region: 'Global',
      label: 'Other jurisdictions',
      summary:
        'Analogous but not identical rules apply elsewhere. The cryptographic bar is consistent; procedural bars vary.',
      claims: [
        {
          title: 'United Kingdom',
          body: 'Civil Evidence Act 1995 and Criminal Procedure Rules. Electronic signatures covered by the Electronic Communications Act 2000. UK eIDAS (retained EU law) is substantially similar to EU eIDAS.',
          airProvides:
            'AIR\'s cryptographic primitives meet the UK technical bar for authentication. Procedural chain-of-custody is operator-side.',
          sourceLabel: 'Civil Evidence Act 1995',
          sourceUrl: 'https://www.legislation.gov.uk/ukpga/1995/38/contents',
        },
        {
          title: 'Canada',
          body: 'Canada Evidence Act sections 31.1 to 31.8 on electronic documents. Similar authentication framework to FRE.',
          airProvides: 'Same cryptographic chain, same certification pattern, adjust to Canadian procedural form.',
          sourceLabel: 'Canada Evidence Act',
          sourceUrl: 'https://laws-lois.justice.gc.ca/eng/acts/c-5/',
        },
        {
          title: 'Singapore',
          body: 'Electronic Transactions Act. Evidence Act provisions on computer output.',
          airProvides: 'Signature and hash verification clears the technical bar; local procedural documentation required.',
          sourceLabel: 'Electronic Transactions Act',
          sourceUrl: 'https://sso.agc.gov.sg/Act/ETA2010',
        },
        {
          title: 'Australia',
          body: 'Evidence Act 1995 (Cth) Part 2.3 on electronic records.',
          airProvides: 'Same primitives, same custodian certification approach, Australian form.',
          sourceLabel: 'Evidence Act 1995 (Cth)',
          sourceUrl: 'https://www.legislation.gov.au/Details/C2016C01017',
        },
      ],
    },
  ];

  let activeId = $state('fre');
  let active = $derived(FRAMEWORKS.find((f) => f.id === activeId) ?? FRAMEWORKS[0]);
</script>

<div class="glass-panel rounded-lg overflow-hidden">
  <!-- Tabs -->
  <div class="border-b border-white/10 flex overflow-x-auto">
    {#each FRAMEWORKS as framework}
      <button
        type="button"
        class="px-4 sm:px-6 py-4 font-mono text-[11px] uppercase tracking-[0.18em] whitespace-nowrap transition-colors border-r border-white/10 last:border-r-0 {activeId ===
        framework.id
          ? 'bg-white/5 text-white border-b-2 border-b-brand-red -mb-px'
          : 'text-zinc-500 hover:text-white hover:bg-white/5'}"
        onclick={() => (activeId = framework.id)}
      >
        <span class="block">{framework.short}</span>
        <span class="block text-[9px] text-zinc-600 font-sans normal-case tracking-normal mt-0.5">
          {framework.region}
        </span>
      </button>
    {/each}
  </div>

  <div class="p-6 sm:p-8">
    <!-- Framework header -->
    <div class="mb-8 pb-6 border-b border-white/5">
      <div class="font-mono text-[10px] uppercase tracking-[0.18em] text-brand-red mb-2">
        {active.region}
      </div>
      <h3 class="text-2xl sm:text-3xl font-bold text-white mb-3">{active.label}</h3>
      <p class="text-zinc-400 leading-relaxed">{active.summary}</p>
    </div>

    <!-- Claims -->
    <div class="space-y-6">
      {#each active.claims as claim}
        <div class="grid md:grid-cols-[1fr_1fr] gap-6 md:gap-8 pb-6 border-b border-white/5 last:border-b-0 last:pb-0">
          <div>
            <div class="font-mono text-[10px] uppercase tracking-wider text-zinc-500 mb-2">
              The rule
            </div>
            <div class="text-white font-semibold mb-2">{claim.title}</div>
            <p class="text-zinc-400 text-sm leading-relaxed">{claim.body}</p>
            <a
              href={claim.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              class="inline-flex items-center gap-1.5 mt-3 font-mono text-[11px] text-brand-cyan hover:text-white transition-colors"
            >
              {claim.sourceLabel}
              <span aria-hidden="true">↗</span>
            </a>
          </div>
          <div class="border-l-2 border-brand-red/40 pl-6">
            <div class="font-mono text-[10px] uppercase tracking-wider text-brand-red mb-2">
              What AIR provides
            </div>
            <p class="text-zinc-200 text-sm leading-relaxed">{claim.airProvides}</p>
          </div>
        </div>
      {/each}
    </div>
  </div>
</div>
