// Regenerates the precomputed land-dot lattice for DotMap so the browser never
// runs geoContains (which froze the page for many seconds). Run from vindicara-site:
//   node scripts/gen-lattice.mjs
import { readFileSync, writeFileSync } from 'fs';
import { geoContains } from 'd3-geo';
import { feature } from 'topojson-client';

const world = JSON.parse(readFileSync('node_modules/world-atlas/countries-110m.json'));
const land = feature(world, world.objects.countries);
const t0 = Date.now();
const pts = [];
for (let lat = -56; lat <= 80; lat += 2.1) {
  for (let lon = -179; lon <= 179; lon += 2.1) {
    if (geoContains(land, [lon, lat])) pts.push([Math.round(lon * 100) / 100, Math.round(lat * 100) / 100]);
  }
}
const ms = Date.now() - t0;
const out =
  '// Auto-generated by scripts/gen-lattice.mjs. Precomputed land-dot lattice so the\n' +
  '// browser never runs geoContains. Each entry is [lon, lat]. Do not hand-edit.\n' +
  'export const LAND_DOTS = ' + JSON.stringify(pts) + ';\n';
writeFileSync('src/lib/components/landDots.js', out);
console.log(`geoContains pass: ${ms} ms -> ${pts.length} land dots; wrote landDots.js (${(out.length / 1024) | 0} KB)`);
